# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Mocomes' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Mocomes
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'SwiftyDropbox'
  pod 'RAMAnimatedTabBarController'
  pod 'MMPopLabel'
  pod 'RKNotificationHub'
  target 'MocomesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MocomesUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
