# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Mocomes' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Mocomes
    pod 'SwiftyJSON'
    pod 'Firebase/Storage'
    pod 'Firebase/Database'
    pod 'Firebase/Auth'
    pod 'Alamofire'
    pod 'RKNotificationHub'
    pod 'RAMAnimatedTabBarController'
    pod 'MMPopLabel'
    pod 'JSQMessagesViewController' 
  target 'MocomesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MocomesUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
